"""PyInstaller spec file generation for bootstack projects."""

from __future__ import annotations

from pathlib import Path
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from bootstack.cli.config import TtkbConfig


# PyInstaller spec template that reads from bootstack.toml
SPEC_TEMPLATE = '''\
# -*- mode: python ; coding: utf-8 -*-
"""
PyInstaller spec file for {app_name}.

This file is auto-generated by bootstack CLI.
Edit bootstack.toml to change build settings, then regenerate with:
    bootstack promote --pyinstaller --force
"""

import sys
from pathlib import Path

# PyInstaller exec's this spec with SPECPATH (directory of the .spec file)
# in the namespace. __file__ is not defined inside a spec.
PROJECT_ROOT = Path(SPECPATH).parent.parent
CONFIG_PATH = PROJECT_ROOT / "bootstack.toml"

# Ensure we can import bootstack CLI tools
try:
    from bootstack.cli.config import TtkbConfig
except ImportError:
    sys.path.insert(0, str(PROJECT_ROOT / "src"))
    from bootstack.cli.config import TtkbConfig

if not CONFIG_PATH.exists():
    raise FileNotFoundError(f"bootstack.toml not found at {{CONFIG_PATH}}")

config = TtkbConfig.load(CONFIG_PATH)

# Extract settings
APP_NAME = config.app.name
ENTRY_POINT = PROJECT_ROOT / config.app.entry
WINDOWED = config.build.windowed if config.build else True
ONEFILE = config.build.onefile if config.build else False

# Icon handling
ICON_PATH = None
_icon_cfg = config.build.icon if config.build else None
if _icon_cfg and _icon_cfg.path:
    icon_candidate = PROJECT_ROOT / _icon_cfg.path
    if icon_candidate.exists():
        ICON_PATH = str(icon_candidate)
elif _icon_cfg and _icon_cfg.glyph:
    # Generate an .ico from a glyph. No app runs during a build, so colors must
    # be hex — a theme token cannot be resolved and would fail to render.
    if not (_icon_cfg.background.startswith("#") and _icon_cfg.foreground.startswith("#")):
        print(
            "[build.icon] background/foreground must be hex colors (e.g. "
            "'#0d6efd'); theme tokens need a running app. Using the default icon."
        )
    else:
        try:
            from bootstack.images import AppIcon
            out = PROJECT_ROOT / "build" / "app-icon.ico"
            out.parent.mkdir(parents=True, exist_ok=True)
            AppIcon(
                _icon_cfg.glyph,
                background=_icon_cfg.background,
                foreground=_icon_cfg.foreground,
                radius=_icon_cfg.radius,
                shape=_icon_cfg.shape,
            ).save(str(out))
            ICON_PATH = str(out)
        except Exception as exc:
            print(f"Could not generate app icon from glyph {{_icon_cfg.glyph!r}}: {{exc}}")

if ICON_PATH is None:
    # Fall back to the bundled bootstack launch icon (the same artwork
    # the runtime sets via wm_iconphoto, just rendered as a multi-size
    # .ico for Windows). Users can override by setting [build.icon] path
    # in bootstack.toml.
    try:
        import bootstack
        default_icon = Path(bootstack.__file__).parent / "assets" / "bootstack.ico"
        if default_icon.exists():
            ICON_PATH = str(default_icon)
    except Exception:
        pass


# =============================================================================
# Collect data files
# =============================================================================

from glob import glob

datas = []

# Always include bootstack.toml
datas.append((str(CONFIG_PATH), "."))

# Include patterns from config
if config.build and config.build.datas.include:
    for pattern in config.build.datas.include:
        if pattern == "bootstack.toml":
            continue  # Already added
        matches = glob(str(PROJECT_ROOT / pattern), recursive=True)
        for match in matches:
            match_path = Path(match)
            if match_path.is_file():
                rel_path = match_path.relative_to(PROJECT_ROOT)
                dest_dir = str(rel_path.parent) if rel_path.parent != Path(".") else "."
                datas.append((str(match_path), dest_dir))


# =============================================================================
# Collect package data (themes, fonts, icon glyphmaps, locales, etc.)
# =============================================================================

from PyInstaller.utils.hooks import collect_data_files

for _pkg in ("bootstack",):
    try:
        datas += collect_data_files(_pkg)
    except Exception as _e:  # pragma: no cover
        print(f"Warning: Could not collect data files from {{_pkg}}: {{_e}}")


# =============================================================================
# Hidden imports for bootstack
# =============================================================================

hiddenimports = [
    "bootstack",
    "bootstack.style",
    "bootstack.widgets",
    "PIL",
    "PIL._tkinter_finder",
    "babel.numbers",
    "babel.dates",
    "dateutil",
    "dateparser",
]

# babel.bin is a CLI script package whose __init__.py calls exit(1) when
# imported without args; PyInstaller's binary-dependency analyzer
# imports it during package walking and crashes. Excluding it is safe
# because nothing in a bootstack app uses babel's command-line tools.
excludes = [
    "babel.bin",
]


# =============================================================================
# Analysis
# =============================================================================

a = Analysis(
    [str(ENTRY_POINT)],
    pathex=[str(PROJECT_ROOT / "src")],
    binaries=[],
    datas=datas,
    hiddenimports=hiddenimports,
    hookspath=[],
    hooksconfig={{}},
    runtime_hooks=[],
    excludes=excludes,
    noarchive=False,
    optimize=0,
)


# =============================================================================
# Build
# =============================================================================

pyz = PYZ(a.pure)

if ONEFILE:
    exe = EXE(
        pyz,
        a.scripts,
        a.binaries,
        a.datas,
        [],
        name=APP_NAME,
        debug=False,
        bootloader_ignore_signals=False,
        strip=False,
        upx=True,
        upx_exclude=[],
        runtime_tmpdir=None,
        console=not WINDOWED,
        disable_windowed_traceback=False,
        argv_emulation=False,
        target_arch=None,
        codesign_identity=None,
        entitlements_file=None,
        icon=ICON_PATH,
    )
else:
    exe = EXE(
        pyz,
        a.scripts,
        [],
        exclude_binaries=True,
        name=APP_NAME,
        debug=False,
        bootloader_ignore_signals=False,
        strip=False,
        upx=True,
        console=not WINDOWED,
        disable_windowed_traceback=False,
        argv_emulation=False,
        target_arch=None,
        codesign_identity=None,
        entitlements_file=None,
        icon=ICON_PATH,
    )

    coll = COLLECT(
        exe,
        a.binaries,
        a.datas,
        strip=False,
        upx=True,
        upx_exclude=[],
        name=APP_NAME,
    )
'''


def generate_spec(
    config: TtkbConfig,
    project_root: Path,
    output_path: Path,
) -> None:
    """Generate a PyInstaller spec file.

    Args:
        config: The project configuration.
        project_root: Root directory of the project.
        output_path: Path to write the spec file.
    """
    content = SPEC_TEMPLATE.format(
        app_name=config.app.name,
    )

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(content, encoding="utf-8")
