blank_issues_enabled: false
contact_links:
  - name: Questions
    url: https://github.com/israel-dryer/bootstack/discussions/new
    about: "Ask a question in the discussion forum"
  - name: Documentation
    url: https://bootstack.org/
    about: "bootstack's documentation"
