"""Built-in color themes, defined as `Theme` instances.

These replace the former `assets/themes/*.json` files so themes are plain
Python objects — importable, type-checked, and free of any asset-bundling
step (no PyInstaller `--add-data` needed). They are installed into the theme
registry by `install_builtin_themes`, called from the theme provider.
"""
from __future__ import annotations

from bootstack.style.theme import Theme

BOOTSTRAP_LIGHT = Theme(
    name="bootstrap-light",
    display_name="Bootstrap Light",
    mode="light",
    foreground="#212529",
    background="#ffffff",
    white="#ffffff",
    black="#000000",
    shades={
        "blue": "#0d6efd",
        "indigo": "#6610f2",
        "purple": "#6f42c1",
        "red": "#dc3545",
        "orange": "#fd7e14",
        "yellow": "#ffc107",
        "green": "#198754",
        "teal": "#20c997",
        "cyan": "#0dcaf0",
        "gray": "#adb5bd",
        "pink": "#d63384",
    },
    semantic={
        "primary": "blue[600]",
        "secondary": "gray[700]",
        "info": "cyan[600]",
        "success": "green[600]",
        "warning": "yellow[600]",
        "danger": "red[600]",
    },
)

BOOTSTRAP_DARK = Theme(
    name="bootstrap-dark",
    display_name="Bootstrap Dark",
    mode="dark",
    foreground="#f8f9fa",
    background="#212529",
    white="#ffffff",
    black="#000000",
    shades={
        "blue": "#0d6efd",
        "indigo": "#6610f2",
        "purple": "#6f42c1",
        "red": "#dc3545",
        "orange": "#fd7e14",
        "yellow": "#ffc107",
        "green": "#198754",
        "teal": "#20c997",
        "cyan": "#0dcaf0",
        "gray": "#adb5bd",
        "pink": "#d63384",
    },
    semantic={
        "primary": "blue[400]",
        "secondary": "gray[400]",
        "info": "cyan[400]",
        "success": "green[400]",
        "warning": "yellow[400]",
        "danger": "red[400]",
    },
)

AMBER_LIGHT = Theme(
    name="amber-light",
    display_name="Amber Light",
    mode="light",
    foreground="#212529",
    background="#f7f2e9",
    white="#ffffff",
    black="#000000",
    shades={
        "blue": "#0d6efd",
        "indigo": "#6610f2",
        "purple": "#6f42c1",
        "red": "#dc3545",
        "orange": "#fd7e14",
        "yellow": "#ffc107",
        "green": "#198754",
        "teal": "#20c997",
        "cyan": "#0dcaf0",
        "gray": "#adb5bd",
        "pink": "#d63384",
    },
    semantic={
        "primary": "orange[600]",
        "secondary": "yellow[600]",
        "info": "cyan[600]",
        "success": "green[600]",
        "warning": "yellow[600]",
        "danger": "red[600]",
    },
)

AMBER_DARK = Theme(
    name="amber-dark",
    display_name="Amber Dark",
    mode="dark",
    foreground="#f8f9fa",
    background="#18130a",
    white="#ffffff",
    black="#000000",
    shades={
        "blue": "#0d6efd",
        "indigo": "#6610f2",
        "purple": "#6f42c1",
        "red": "#dc3545",
        "orange": "#fd7e14",
        "yellow": "#ffc107",
        "green": "#198754",
        "teal": "#20c997",
        "cyan": "#0dcaf0",
        "gray": "#adb5bd",
        "pink": "#d63384",
    },
    semantic={
        "primary": "orange[400]",
        "secondary": "yellow[400]",
        "info": "cyan[400]",
        "success": "green[400]",
        "warning": "yellow[400]",
        "danger": "red[400]",
    },
)

AURORA_LIGHT = Theme(
    name="aurora-light",
    display_name="Aurora Light",
    mode="light",
    foreground="#212529",
    background="#f3f8f4",
    white="#ffffff",
    black="#000000",
    shades={
        "blue": "#0d6efd",
        "indigo": "#6610f2",
        "purple": "#6f42c1",
        "red": "#dc3545",
        "orange": "#fd7e14",
        "yellow": "#ffc107",
        "green": "#198754",
        "teal": "#20c997",
        "cyan": "#0dcaf0",
        "gray": "#adb5bd",
        "pink": "#d63384",
    },
    semantic={
        "primary": "teal[600]",
        "secondary": "purple[600]",
        "info": "cyan[600]",
        "success": "green[600]",
        "warning": "yellow[600]",
        "danger": "pink[600]",
    },
)

AURORA_DARK = Theme(
    name="aurora-dark",
    display_name="Aurora Dark",
    mode="dark",
    foreground="#f8f9fa",
    background="#071514",
    white="#ffffff",
    black="#000000",
    shades={
        "blue": "#0d6efd",
        "indigo": "#6610f2",
        "purple": "#6f42c1",
        "red": "#dc3545",
        "orange": "#fd7e14",
        "yellow": "#ffc107",
        "green": "#198754",
        "teal": "#20c997",
        "cyan": "#0dcaf0",
        "gray": "#adb5bd",
        "pink": "#d63384",
    },
    semantic={
        "primary": "teal[400]",
        "secondary": "purple[400]",
        "info": "cyan[400]",
        "success": "green[400]",
        "warning": "yellow[400]",
        "danger": "pink[400]",
    },
)

FOREST_LIGHT = Theme(
    name="forest-light",
    display_name="Forest Light",
    mode="light",
    foreground="#212529",
    background="#f3f8f4",
    white="#ffffff",
    black="#000000",
    shades={
        "blue": "#0d6efd",
        "indigo": "#6610f2",
        "purple": "#6f42c1",
        "red": "#dc3545",
        "orange": "#fd7e14",
        "yellow": "#ffc107",
        "green": "#198754",
        "teal": "#20c997",
        "cyan": "#0dcaf0",
        "gray": "#adb5bd",
        "pink": "#d63384",
    },
    semantic={
        "primary": "green[600]",
        "secondary": "teal[600]",
        "info": "teal[600]",
        "success": "green[600]",
        "warning": "yellow[600]",
        "danger": "red[600]",
    },
)

FOREST_DARK = Theme(
    name="forest-dark",
    display_name="Forest Dark",
    mode="dark",
    foreground="#f8f9fa",
    background="#0b1610",
    white="#ffffff",
    black="#000000",
    shades={
        "blue": "#0d6efd",
        "indigo": "#6610f2",
        "purple": "#6f42c1",
        "red": "#dc3545",
        "orange": "#fd7e14",
        "yellow": "#ffc107",
        "green": "#198754",
        "teal": "#20c997",
        "cyan": "#0dcaf0",
        "gray": "#adb5bd",
        "pink": "#d63384",
    },
    semantic={
        "primary": "green[400]",
        "secondary": "teal[400]",
        "info": "teal[400]",
        "success": "green[400]",
        "warning": "yellow[400]",
        "danger": "red[400]",
    },
)

OCEAN_LIGHT = Theme(
    name="ocean-light",
    display_name="Ocean Light",
    mode="light",
    foreground="#212529",
    background="#e9f7fb",
    white="#ffffff",
    black="#000000",
    shades={
        "blue": "#0d6efd",
        "indigo": "#6610f2",
        "purple": "#6f42c1",
        "red": "#dc3545",
        "orange": "#fd7e14",
        "yellow": "#ffc107",
        "green": "#198754",
        "teal": "#20c997",
        "cyan": "#0dcaf0",
        "gray": "#adb5bd",
        "pink": "#d63384",
    },
    semantic={
        "primary": "cyan[600]",
        "secondary": "blue[600]",
        "info": "blue[600]",
        "success": "teal[600]",
        "warning": "yellow[600]",
        "danger": "red[600]",
    },
)

OCEAN_DARK = Theme(
    name="ocean-dark",
    display_name="Ocean Dark",
    mode="dark",
    foreground="#f8f9fa",
    background="#07141f",
    white="#ffffff",
    black="#000000",
    shades={
        "blue": "#0d6efd",
        "indigo": "#6610f2",
        "purple": "#6f42c1",
        "red": "#dc3545",
        "orange": "#fd7e14",
        "yellow": "#ffc107",
        "green": "#198754",
        "teal": "#20c997",
        "cyan": "#0dcaf0",
        "gray": "#adb5bd",
        "pink": "#d63384",
    },
    semantic={
        "primary": "cyan[400]",
        "secondary": "blue[400]",
        "info": "blue[400]",
        "success": "teal[400]",
        "warning": "yellow[400]",
        "danger": "red[400]",
    },
)

PYDATA_LIGHT = Theme(
    name="pydata-light",
    display_name="PyData Light",
    mode="light",
    foreground="#222832",
    background="#ffffff",
    white="#ffffff",
    black="#000000",
    shades={
        "teal": "#0a7d91",
        "violet": "#8045e5",
        "pink": "#c132af",
        "red": "#dc3545",
        "orange": "#fd7e14",
        "yellow": "#ffc107",
        "green": "#198754",
        "cyan": "#0dcaf0",
        "gray": "#677384",
    },
    semantic={
        "primary": "teal[500]",
        "secondary": "violet[500]",
        "info": "cyan[600]",
        "success": "green[600]",
        "warning": "yellow[600]",
        "danger": "red[600]",
    },
)

PYDATA_DARK = Theme(
    name="pydata-dark",
    display_name="PyData Dark",
    mode="dark",
    foreground="#ced6dd",
    background="#14181e",
    white="#ffffff",
    black="#000000",
    shades={
        "teal": "#0a7d91",
        "violet": "#8045e5",
        "pink": "#c132af",
        "red": "#dc3545",
        "orange": "#fd7e14",
        "yellow": "#ffc107",
        "green": "#198754",
        "cyan": "#0dcaf0",
        "gray": "#677384",
    },
    semantic={
        "primary": "teal[400]",
        "secondary": "violet[400]",
        "info": "cyan[400]",
        "success": "green[400]",
        "warning": "yellow[400]",
        "danger": "red[400]",
    },
)

ROSE_LIGHT = Theme(
    name="rose-light",
    display_name="Rose Light",
    mode="light",
    foreground="#212529",
    background="#fff5f8",
    white="#ffffff",
    black="#000000",
    shades={
        "blue": "#0d6efd",
        "indigo": "#6610f2",
        "purple": "#6f42c1",
        "red": "#dc3545",
        "orange": "#fd7e14",
        "yellow": "#ffc107",
        "green": "#198754",
        "teal": "#20c997",
        "cyan": "#0dcaf0",
        "gray": "#adb5bd",
        "pink": "#d63384",
    },
    semantic={
        "primary": "pink[600]",
        "secondary": "red[600]",
        "info": "cyan[600]",
        "success": "green[600]",
        "warning": "yellow[600]",
        "danger": "red[600]",
    },
)

ROSE_DARK = Theme(
    name="rose-dark",
    display_name="Rose Dark",
    mode="dark",
    foreground="#f8f9fa",
    background="#190910",
    white="#ffffff",
    black="#000000",
    shades={
        "blue": "#0d6efd",
        "indigo": "#6610f2",
        "purple": "#6f42c1",
        "red": "#dc3545",
        "orange": "#fd7e14",
        "yellow": "#ffc107",
        "green": "#198754",
        "teal": "#20c997",
        "cyan": "#0dcaf0",
        "gray": "#adb5bd",
        "pink": "#d63384",
    },
    semantic={
        "primary": "pink[400]",
        "secondary": "red[400]",
        "info": "cyan[400]",
        "success": "green[400]",
        "warning": "yellow[400]",
        "danger": "red[400]",
    },
)

#: All built-in themes, in display order.
BUILTIN_THEMES = [
    BOOTSTRAP_LIGHT,
    BOOTSTRAP_DARK,
    AMBER_LIGHT,
    AMBER_DARK,
    AURORA_LIGHT,
    AURORA_DARK,
    FOREST_LIGHT,
    FOREST_DARK,
    OCEAN_LIGHT,
    OCEAN_DARK,
    PYDATA_LIGHT,
    PYDATA_DARK,
    ROSE_LIGHT,
    ROSE_DARK,
]


def install_builtin_themes() -> None:
    """Register every built-in theme into the theme registry (idempotent)."""
    for theme in BUILTIN_THEMES:
        theme.install()
